### ISSUE TITLE
This doesn't follow the same URL conventions as express.js.

### ISSUE THREAD

**Issue by johnfn** [rawrmaan/restyped-express-async#1]
You're using `app.use` internally, but `app.use` does not follow the same specifications for url matching as, say, `app.get`.

For example, if you define `GET /api/users` and `GET /api/users/foo`, a request to `/api/users/foo` could actually match the route defined for `api/users`.

**Comment by johnfn** [comment]
I managed to fix this by rewriting this line https://github.com/rawrmaan/restyped-express-async/blob/master/index.ts#L27

to this:

`        app[method.toLowerCase()](path, function (req, res, next) {`

but as I can't understand why you were using `app.use()` in the first place, I'm not sure that this is a good solution.

**Comment by rawrmaan** [comment]
Yeah, that was dumb. Fixed in 31967069bf616058a5856e99e01719bf7a7c9045
